\Name{Grab the Release Dates}

\Problem

How to discover the release dates?

\Context

releases are important events. They help to determine phases in the software lifecycle. The activity in a project that is near release date may be different from the activity in regular periods. For example, in Eclipse/Platform, verifications are much more frequent just before a release.

\Solution

project websites do not usually keep info about all the previous releases. Fetch previous versions of the sites using The Internet Archive, archive.org. Other solution is look for tags in the version control system.